version: "3.8"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres${POSTGRES_VERSION}:/var/lib/postgres/data${POSTGRES_VERSION} #Data volume
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_PORT: ${POSTGRES_PORT}
    #restart: unless-stopped
    logging:
      options:
        max-size: 50M
